project_id = "rtmcisfdtnmdytvnmptx"

[functions.generate-page]
verify_jwt = true

[functions.send-reminders]
verify_jwt = false

[functions.disable-reminders]
verify_jwt = false

[functions.create-hero]
verify_jwt = true

[functions.generate-hero-portrait]
verify_jwt = false

[functions.get-image-url]
verify_jwt = true
